Router.map(function(){
	this.route('UserHome',{
		path:'/users/:userid',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'UserHomeHeader':{to:'header'}
		},
		data:function(){
			return {
				User:Meteor.users.findOne({_id:this.params.userid})
			};
		}
	});
	this.route('GameHome',{
		path:'users/:userid/playGame/:gameid',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'GameHomeHeader':{to:'header'}
		},
		onRun:function(){
			Events.onStartGame(this.params.userid,this.params.gameid);
		},
		onStop:function(){
			Events.onEndGame(this.params.userid,this.params.gameid);
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid}),
				Game:Games.findOne({_id:this.params.gameid})
			};
		}
	});
	this.route('GameRound',{
		path:'users/:userid/playGame/:gameid/round/:roundno',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'GameRoundHeader':{to:'header'}
		},
		onRun:function(){
			Events.onStartRound(this.params.userid,this.params.gameid,this.params.roundno);
			Session.set("questionNo",1);
		},
		onStop:function(){
			Events.onEndRound(this.params.userid,this.params.gameid,this.params.roundno);
			Session.set("questionNo",1);
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid}),
				Game:Games.findOne({_id:this.params.gameid}),
				roundno:this.params.roundno
			};
		}
	});
	this.route('DeveloperConsole',{
		path:'users/:userid/developerConsole',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'DeveloperConsoleHeader':{to:'header'}
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid}),
				DeveloperGames:Games.find({creator:this.params.userid})
			};
		}
	});
	this.route('NewGame',{
		path:'users/:userid/newGame',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'NewGameHeader':{to:'header'}
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid})
			};
		}
	});
	this.route('Login',{
		path:'/',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'LoginHeader':{to:'header'}
		}
	});
	this.route('ManageGame',{
		path:'users/:userid/manageGame/:gameid',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'ManageGameHeader':{to:'header'}
		},
		data:function(){
			return {
				User:Meteor.users.findOne({_id:this.params.userid}),
			  Game:Games.findOne({_id:this.params.gameid})
			};
		}
	});
	this.route('ManageMarathon',{
		path:'users/:userid/manageMarathon/:marathonid',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'ManageMarathonHeader':{to:'header'}
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid}),
				Marathon:Marathons.findOne({_id:this.params.marathonid})
			};
		}
	});
	this.route('NewMarathon',{
		path:'users/:userid/newMarathon',
		layoutTemplate:'LayoutTemplate',
		yieldTemplates:{
			'NewMarathonHeader':{to:'header'}
		},
		data:function(){
			return {
			  User:Meteor.users.findOne({_id:this.params.userid})
			};
		}
	});
});
